<?php
$highlight_regex["sql"] = [
['code-comment',  '/(.*?)(--.*?\n|\/\*.*?\*\/)(.*)/s'],
['code-string',   '/(.*?)("(?:[^"\\\\]+|\\\\.)*"|\'(?:[^\\\'\\\\]+|\\\\.)*\\\')(.*)/s'],
['code-number',   '/(.*?\W)(#\d{6}|#\d{3}|-?(?:\d+?\.\d+?|\.\d+?|\d+?)%?|0x\d+?)(\W.*)/s'],
['code-keyword',  '/(.*?)\b(a(?:|dd|gent|ggregate|ll|lter|nd|ny|rray|rrow|s|sc|t|ttribute|uthid|vg)|b(?:egin|etween|file_base|inary|lob_base|lock|ody|oth|ound|ulk|y|yte)|c(?:|all|alling|ascade|ase|har|haracter|har_base|harset|harsetform|harsetid|heck|lob_base|lose|luster|lusters|olauth|ollect|olumns|omment|ommit|ommitted|ompiled|ompress|onnect|onstant|onstructor|ontext|onvert|ount|rash|reate|urrent|ursor|ustomdatum)|d(?:angling|ata|ate|ate_base|ay|ecimal|eclare|efault|efine|elete|esc|eterministic|istinct|ouble|rop|uration)|e(?:lement|lse|lsif|mpty|nd|scape|xcept|xception|xceptions|xclusive|xecute|xists|xit|xternal)|f(?:etch|inal|ixed|loat|or|orall|orce|orm|rom|unction)|g(?:eneral|oto|rant|roup)|h(?:ash|aving|eap|idden|our)|i(?:dentified|f|mmediate|n|ncluding|ndex|ndexes|ndicator|ndices|nfinite|nsert|nstantiable|nt|nterface|ntersect|nterval|nto|nvalidate|s|solation)|j(?:ava)|l(?:anguage|arge|eading|ength|evel|ibrary|ike|ike2|ike4|ikec|imit|imited|ocal|ock|ong|oop)|m(?:ap|ax|axlen|ember|erge|in|inus|inute|od|ode|odify|onth|ultiset)|n(?:an|ational|ative|char|ew|ocompress|ocopy|ot|owait|ull|umber_base)|o(?:bject|cicoll|cidate|cidatetime|ciduration|ciinterval|ciloblocator|cinumber|ciraw|ciref|cirefcursor|cirowid|cistring|citype|f|n|nly|paque|pen|perator|ption|r|racle|radata|rder|rganization|rlany|rlvary|thers|ut|verlaps|verriding)|p(?:ackage|arallel_enable|arameter|arameters|artition|ascal|ipe|ipelined|ragma|recision|rior|rivate|rocedure|ublic)|r(?:aise|ange|aw|ead|ecord|ef|eference|em|emainder|ename|esource|esult|eturn|eturning|everse|evoke|ollback|ow)|s(?:ample|ave|avepoint|b1|b2|b4|econd|egment|elect|elf|eparate|equence|erializable|et|hare|hort|ize|ize_t|ome|parse|ql|qlcode|qldata|qlname|qlstate|tandard|tart|tatic|tddev|tored|tring|truct|tyle|ubmultiset|ubpartition|ubstitutable|ubtype|um|ynonym)|t(?:abauth|able|do|he|hen|ime|imestamp|imezone_abbr|imezone_hour|imezone_minute|imezone_region|o|railing|ransac|ransactional|rusted|ype)|u(?:b1|b2|b4|nder|nion|nique|nsigned|ntrusted|pdate|se|sing)|v(?:alist|alue|alues|ariable|ariance|array|arying|iew|iews|oid)|w(?:hen|here|hile|ith|ork|rapped|rite)|y(?:ear)|z(?:one))\b(.*)/si'],
['code-function', '/(.*?)([a-zA-Z0-9_]+)(\s*\(.*)/s'],
['code-symbol',   "/(.*?)([<>\\\\])(.*)/s"],
['code-symbol',   "/(.*?)([-$!%^*()+|~=`{}[:;?,.@#&_\/\]]+)(.*)/s"],
['code-allcaps',  '/(.*?)(\b[A-Z]+\b)(.*)/s'],
];
